# Site settings
title: Mark Matyas
email: mynameistechno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mynameistechno.github.io/" # the base hostname & protocol for your site
twitter_username: brazill
github_username:  mynameistechno

# Build settings
markdown: kramdown

links:
  - https://github.com/mynameistechno/finderjs
  - https://www.linkedin.com/in/markmatyas
