# Site settings
title: Mark Matyas
email: mark@matyas.dev
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://markmatyas.dev/" # the base hostname & protocol for your site
twitter_username: brazill
github_username:  mynameistechno

# Build settings
markdown: kramdown

links:
  "Qualcomm Innovation Center": "https://github.com/quic"
  "TODO Group": "https://todogroup.org/"
  "FinderJS: Browse hierarchical data in columns, similar to OS X's Finder": "https://markmatyas.dev/finderjs/"
  ClearlyDefined: "https://clearlydefined.io/about"
  Resume: "https://markmatyas.dev/resume"
