# Site settings
title: Mark Matyas
email: mark@matyas.dev
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://markmatyas.dev/" # the base hostname & protocol for your site
twitter_username: brazill
github_username:  mynameistechno

# Build settings
markdown: kramdown

links:
  Resume: "https://markmatyas.dev/resume"
  "FinderJS: Browse hierarchical data in columns, similar to OS X's Finder": "https://markmatyas.dev/finderjs/"
  ClearlyDefined: "https://clearlydefined.io/about"
  LinkedIn: "https://www.linkedin.com/in/markmatyas"